name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag qqanly/clothes-shop-spring-boot:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u qqanly --password-stdin

      - name: Push to Docker Hub
        run: docker push qqanly/clothes-shop-spring-boot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Deploy to Server using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull qqanly/clothes-shop-spring-boot:latest
            

            echo "Stopping and removing old containers..."
            docker-compose stop app
            docker-compose rm -f app
            
            echo "Starting up containers with Docker Compose..."
            docker-compose up -d
            
            echo "Deployment completed!"
